# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r_build_args: '--no-build-vignettes'
addons:
  apt:
    packages:
      - libmagick++-dev

after_success:
  - Rscript -e 'covr::codecov()'